services:
  web:
    build: .
    command: flask -A app run
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLASK_RUN_HOST=0.0.0.0
    # volumes:
    #   - ./certificate_reports:/app/certificate_reports
    networks:
      - keywatch

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - keywatch

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    # volumes:
    #   - ./certificate_reports:/app/certificate_reports
    networks:
      - keywatch

  mongo:
    image: mongo:noble
    ports:
      - "27107:27107"
    networks:
      - keywatch

networks:
  keywatch:
    driver: bridge
